server:
  port: 9001
  shutdown: graceful
  servlet:
    context-path: /api/ticket-system
  tomcat:
    connection-timeout: 1s
    keep-alive-timeout: 15s
    threads:
      max: 100
      min-spare: 20
    max-connections: 10000
    accept-count: 100
    max-swallow-size: 2MB
    max-http-form-post-size: 2MB

spring:
  application:
    name: ticket-system
  output:
    ansi:
      enabled: always
  jackson:
    visibility:
      getter: none
      is-getter: none
      field: any
      setter: none
    default-property-inclusion: non_empty
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      adjust-dates-to-context-time-zone: false
    time-zone: UTC
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:ticket_db}
    username: ${DB_USER:user}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
    show-sql: false
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    clean-disabled: true
    out-of-order: ${FLYWAY_OUT_OF_ORDER:false}
    ignore-migration-patterns: '*:ignored'
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 2000ms
      connect-timeout: 2000ms
      client-type: lettuce
  cache:
    type: redis
    redis:
      time-to-live: 3600
      cache-null-values: false
      use-key-prefix: true
      key-prefix: user_

management:
  endpoints:
    web:
      base-path: /admin
      exposure:
        include: refresh, configprops, env, flyway, health, metrics, heapdump, info, loggers, mappings, prometheus
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
    redis:
      enabled: true
    db:
      enabled: true
  endpoint:
    shutdown:
      access: unrestricted
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
      group:
        readiness:
          include: db, redis, diskSpace
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
      service: ${spring.application.name}
      environment: ${ENVIRONMENT:development}
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5, 0.9, 0.95, 0.99
    export:
      prometheus:
        enabled: true
      otlp:
        enabled: true
        url: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://otel-collector:4318/v1/metrics}
        headers:
          Authorization: ${OTEL_EXPORTER_OTLP_HEADERS:}
        step: 10s
  tracing:
    enabled: true
    sampling:
      probability: 1.0
    export:
      otlp:
        endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://otel-collector:4318}
    propagation:
      consume: b3, w3c
      produce: b3, w3c
  otlp:
    tracing:
      endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://otel-collector:4318/v1/traces}
      headers:
        Authorization: ${OTEL_EXPORTER_OTLP_HEADERS:}
    metrics:
      endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://otel-collector:4318/v1/metrics}
      headers:
        Authorization: ${OTEL_EXPORTER_OTLP_HEADERS:}

logging:
  level:
    root: INFO
    com.xeppelin: ${LOG_LEVEL:INFO}
    org.springframework: INFO
    org.hibernate: INFO
  pattern:
    level: "%5p [${spring.application.name},%X{traceId:-},%X{spanId:-}]"
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %5p [${spring.application.name},%X{traceId:-},%X{spanId:-}] %c{1} : %m%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %5p [${spring.application.name},%X{traceId:-},%X{spanId:-}] %c{1} : %m%n"

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    try-it-out-enabled: true
    operations-sorter: method
    tags-sorter: alpha
    filter: true
    display-request-duration: true
    display-operation-id: true
    show-extensions: true
    show-common-extensions: true
    default-models-expand-depth: 1
    default-model-expand-depth: 1
    doc-expansion: none
    persist-authorization: true
    config-url: /v3/api-docs/swagger-config
    url: /v3/api-docs
  api-docs:
    path: /v3/api-docs
    enabled: true
    resolve-schema-properties: true
  show-actuator: false
  group-configs:
    - group: 'ticket-management'
      display-name: 'Ticket Management API'
      paths-to-match: '/tickets/**'
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  writer-with-default-pretty-printer: true

app:
  ticket:
    reservation:
      max-reservations-per-session: 5
      max-quantity-per-reservation: 10
      max-extension-duration: PT1H        # ISO-8601 duration format (1 hour)
      default-reservation-duration: PT15M  # ISO-8601 duration format (15 minutes)
      expiration-grace-period: PT1M       # ISO-8601 duration format (1 minute)


